// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddMenu():Promise<void>;

export function CheckServer(arg1:string):Promise<boolean>;

export function ExecJs(arg1:string):Promise<void>;

export function LoadConfig():Promise<main.configData>;

export function MessageDialog():Promise<string>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function OpenMultipleFilesDialog():Promise<Array<string>>;

export function SaveFileDialog():Promise<string>;

export function SubmitConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;
