// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMenu() {
  return window['go']['main']['App']['AddMenu']();
}

export function CheckServer(arg1) {
  return window['go']['main']['App']['CheckServer'](arg1);
}

export function ExecJs(arg1) {
  return window['go']['main']['App']['ExecJs'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function MessageDialog() {
  return window['go']['main']['App']['MessageDialog']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenMultipleFilesDialog() {
  return window['go']['main']['App']['OpenMultipleFilesDialog']();
}

export function SaveFileDialog() {
  return window['go']['main']['App']['SaveFileDialog']();
}

export function SubmitConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SubmitConfig'](arg1, arg2, arg3, arg4, arg5);
}
